### ISSUE TITLE
Cant connect to my p1ib

### ISSUE THREAD

**Issue by TibiaBubble** [whyz/homey-p1ib#3]
Hej,
Det går inte att connecta till min P1ib som är i elskåpet.
Jag kommer åt de via min pc och mobil men homey appen verkar inte komma åt enheten.

koden jag fick är: d6a0d214-549d-4cca-bbf0-d7b67588c1b4

**Comment by whyz** [comment]
Hej! Det verkar som om nya homey är lite annorlunda. Det finns en testversion (1.0.6) av appen som förmodligen löser ditt problem. Jag hoppas kunna släppa den inom kort.

**Comment by TibiaBubble** [comment]
> Hej! Det verkar som om nya homey är lite annorlunda. Det finns en testversion (1.0.6) av appen som förmodligen löser ditt problem. Jag hoppas kunna släppa den inom kort.

Jaha jag förstår, då får jag avvakta tills den nya versionen kommer ut eller finns det ett sätt att installera beta appar?

**Comment by whyz** [comment]
Du borde se import/export. Vilka värden saknar du?

**Comment by TibiaBubble** [comment]
Jo jag kan se import/export jag ville mer kunna få möjligheten att se import och export ihop. Så att jag ser hur mycket jag importerar och exporterar 😅
Om det nu är möjligt dvs.

nu när jag exporterar så har jag noll förbrukning och skulle gärna vilja se exporten utan att behöva klicka 😂😅🥹🥹🥹

annars älskar jag appen och du ska ha en stor tumme upp för din insats!


![IMG_1929](https://user-images.githubusercontent.com/122465540/236662460-84df4d47-7b85-431e-b599-9e75f99d8959.jpeg)
![IMG_1930](https://user-images.githubusercontent.com/122465540/236662461-1c3f5b2a-e558-447e-960f-efada87c2e6d.jpeg)

**Comment by whyz** [comment]
Hej @TibiaBubble , jag stänger den här så får du göra en ny feature request om du vill ha en kombinerad sensor. :)
