### ISSUE TITLE
Enhet är inte tillgänglig

### ISSUE THREAD

**Issue by hmarkstrom** [whyz/homey-p1ib#4]
Efter att Homey Pro (2019) uppdaterades till 8.1.5 så tappar appen kontakt kort efter appen är installerad.

**Comment by hmarkstrom** [comment]
Har gjort det. Här är koden du ska ha:
36a812ab-daca-4654-b008-1a8701d39f20

**Comment by whyz** [comment]
Hm det ser ut som en timeout. Kan du nå webgränssnittet på din p1ib?

**Comment by hmarkstrom** [comment]
Hej

 

Ja det går bra att nå webgränssnittet.

 

 

Från: whyz ***@***.***> 
Skickat: den 1 juli 2023 16:56
Till: whyz/homey-p1ib ***@***.***>
Kopia: hmarkstrom ***@***.***>; Author ***@***.***>
Ämne: Re: [whyz/homey-p1ib] Enhet är inte tillgänglig (Issue #4)

 

Hm det ser ut som en timeout. Kan du nå webgränssnittet på din p1ib?

**Comment by whyz** [comment]
Version 1.0.7 finns för test. Inte säkert att det hjälper, men värt ett försök

**Comment by whyz** [comment]
Hej @hmarkstrom , har du testat med 1.0.7?

**Comment by hmarkstrom** [comment]
Hej

 

Hur gör man det?

 

Mvh

 

Håkan

 

 

Från: whyz ***@***.***> 
Skickat: den 6 juli 2023 19:49
Till: whyz/homey-p1ib ***@***.***>
Kopia: hmarkstrom ***@***.***>; Mention ***@***.***>
Ämne: Re: [whyz/homey-p1ib] Enhet är inte tillgänglig (Issue #4)

 

Hej @hmarkstrom <https://github.com/hmarkstrom>  , har du testat med 1.0.7?

**Comment by whyz** [comment]
Hej,

En annan användare i #5 verkar ha liknande problem. I det fallet var p1ib lösenordsskyddad, vilket inte homey-appen stödjer ännu. Har du också aktiverat lösenord i din p1ib?

**Comment by hmarkstrom** [comment]
Hej

 

Har inte gjort det annat än till MQTT funktionen.

 

Mvh

 

Håkan

 

 

Från: whyz ***@***.***> 
Skickat: den 7 juli 2023 21:24
Till: whyz/homey-p1ib ***@***.***>
Kopia: hmarkstrom ***@***.***>; Mention ***@***.***>
Ämne: Re: [whyz/homey-p1ib] Enhet är inte tillgänglig (Issue #4)

 

Hej,

En annan användare i #5 <https://github.com/whyz/homey-p1ib/issues/5>  verkar ha liknande problem. I det fallet var p1ib lösenordsskyddad, vilket inte homey-appen stödjer ännu. Har du också aktiverat lösenord i din p1ib?

**Comment by relnah** [comment]
Hej!

Jag har samma problem. Vet dock ej exakt när det började. Både homey och p1ib är uppdaterade till senaste versioner.
Det jag trodde först var lösenordsskyddet på p1ib som jag aktiverade häromdagen.
Men har avaktiverat det och efter det startat om p1ib appen i homey.
Efter det skapade jag denna diagnostik rapport.
03a5cb58-8f57-44dc-80d0-90a8f9b796f0

**Comment by whyz** [comment]
Hej @relnah , kan du testa med testversionen på https://homey.app/a/nu.ahlner.p1ib/test/ ? Om det beter sig lika illa, skicka en ny diagnosrapport.

**Comment by relnah** [comment]
Nu började det fungera. Nice!

**Comment by relnah** [comment]
1.0.5 funkar inte

1.0.9 test funkar
Diag id även fast det funkade: 92d5865e-168d-41cd-b10a-082addc84462
