### ISSUE TITLE
Enheten är inte tillgänglig

### ISSUE THREAD

**Issue by Supernmes** [whyz/homey-p1ib#5]
Hej!

Jag vet inte om jag borde ha skrivit i andra ärendet som handlar om samma problem.

Jag får "Enheten är inte tillgänglig".

Jag ska ha skrivit ner alla versioner och liknande jag använder i diagnostikraapporten. Hojta till om något saknas!

Jag kan logga in på webgränssnittet och se data. 

När jag lägger till enheten i Homey så hittar den rätt ip-adress följt av :80. Jag har testat ändra till p1ib.local men samma problem.

22d974fc-c208-438e-b480-2916d37ba7ed

Tacksam om du kan se i loggarna vad som blir fel =)

**Comment by whyz** [comment]
Hej,
Jag har publicerat en ny testversion, 1.0.9. Den kommer inte lösa något problem men förhoppningsvis hjälpa till att hitta vad som går fel. Installera den och skicka en diagnostikrapport när det går fel. https://homey.app/a/nu.ahlner.p1ib/test/

**Comment by Supernmes** [comment]
Tjena!

Här är ett anslutningsförsök med version 1.0.9

7ae62233-bf67-45f6-842f-8a21ede691af


Jag kom precis på att jag aktiverade lösenordet igen innan i p1ib enheten. Hojta till om det ställer till det så får jag ta bort det imorgon!

Tack för hjälpen!

**Comment by whyz** [comment]
Hej, 
Ja tyvärr stödjer inte homey-appen lösenordsskyddad p1ib (än). Återkom i morgon när du testat utan :)

**Comment by Supernmes** [comment]
Hej!

Nu anslöt den korrekt. Jag får data från enheten in i Homey. Jag har egentligen inte gjort något annorlunda idag mer än tagit bort lösen. Men det gjorde jag igår också.

2784dfab-0171-4a61-a5c2-ef5a3b7254f1

**Comment by whyz** [comment]
Hej! Okej, så nu funkar allt som det ska?

**Comment by Supernmes** [comment]
Tjena!

Ja den har tuffat på hela dagen nu, inga konstigheter!

Tackar för hjälpen! :)

**Comment by whyz** [comment]
Fint!

**Comment by Supernmes** [comment]
Hej!

Jag skickade in en diagnostikrapport till dig. Fel vid anslutning Efter uppgradering till 1.0.10. 1.0.9 var den version som fungerade för mig, jag vet att den var experimentell men jag missade att bocka ur Automatisk Upgradering. 

Nu i 1.0.10 får jag inte kontakt med enheten. Har testat starta om Appen och även testat ta bort och lägga till enhet. Ser du nått konstigt i loggen?

9f9077ad-5eaf-4121-8e3d-76eb5e17edb3

**Comment by whyz** [comment]
Hej @Supernmes , kan du testa med 1.0.11?

**Comment by Supernmes** [comment]
Hej! 

Hoppade igång direkt med 1.0.11! Tack så mycket!
