### ISSUE TITLE
Active power L1-3 (solar) visar effekt

### ISSUE THREAD

**Issue by Mika-gbg** [whyz/homey-p1ib#8]
Hej,
Nyligen kopplat in p1ib och ser att Active power L1-3 (solar) visar effekt trots att det är kväll därav mörkt ute dvs solcellerna producerar 0.
Ska det vara så eller är något fel på p1ib, mjukvara, elmätaren eller inkopplingen?
Bifogar bild.
![IMG_0346](https://github.com/whyz/homey-p1ib/assets/149713849/72446bd0-329f-49b7-b8de-48059ef59794)

Med vänlig hälsning, 
Mika

**Comment by whyz** [comment]
Hej,
Detta repo är för homey-appen för p1ib. Bättre att ställa din fråga här: https://github.com/remne/p1ib/issues

**Comment by oldest53** [comment]
Det blir så även utan solpaneler.
